class DiseaseInfo {
  final String plantNameAr;
  final String plantNameEn;
  final String conditionAr;
  final String conditionEn;
  final String symptomsAr;
  final String symptomsEn;
  final String treatmentAr;
  final String treatmentEn;

  const DiseaseInfo({
    required this.plantNameAr,
    required this.plantNameEn,
    required this.conditionAr,
    required this.conditionEn,
    required this.symptomsAr,
    required this.symptomsEn,
    required this.treatmentAr,
    required this.treatmentEn,
  });
}

const Map<String, DiseaseInfo> diseaseDictionary = {
  'Apple___Apple_scab': DiseaseInfo(
    plantNameAr: 'تفاح',
    plantNameEn: 'Apple',
    conditionAr: 'جرب التفاح (Apple Scab)',
    conditionEn: 'Apple Scab',
    symptomsAr: 'بقع سوداء أو بنية زيتونية على الأوراق والثمار، وتجعد الأوراق وتساقطها المبكر.',
    symptomsEn: 'Olive green to black spots on leaves and fruit, leaf curling and premature drop.',
    treatmentAr: 'رش مبيدات فطرية محتوية على الكبريت أو النحاس، والتخلص من الأوراق المصابة المتساقطة.',
    treatmentEn: 'Apply sulfur or copper fungicides, and clean up fallen infected leaves immediately.',
  ),
  'Apple___Black_rot': DiseaseInfo(
    plantNameAr: 'تفاح',
    plantNameEn: 'Apple',
    conditionAr: 'العفن الأسود (Black Rot)',
    conditionEn: 'Black Rot',
    symptomsAr: 'نخر فجائي بالثمار مع حلقات مركزية بنية، وظهور بقع دائرية حمراء/بنفسجية على الأوراق.',
    symptomsEn: 'Frogeye spots on leaves (purple rim with brown center), rotten fruit with concentric bands.',
    treatmentAr: 'تقليم الفروع المصابة خلال الخريف، ورش مبيدات فطرية مناسبة وإزالة الفواكه المتعفنة.',
    treatmentEn: 'Prune dead wood during dormancy, remove mummified fruit, and apply protectant fungicides.',
  ),
  'Apple___Cedar_apple_rust': DiseaseInfo(
    plantNameAr: 'تفاح',
    plantNameEn: 'Apple',
    conditionAr: 'صدأ تفاح الأرز (Cedar Apple Rust)',
    conditionEn: 'Cedar Apple Rust',
    symptomsAr: 'بقع برتقالية أو صفراء زاهية على السطح السفلي للأوراق مع هياكل شبيهة بالأنابيب الصغيرة.',
    symptomsEn: 'Bright orange or yellow spots on foliage with tiny tube-like projections on underside.',
    treatmentAr: 'تجنب زراعة أشجار عرعر الأرز بالقرب من التفاح، واستخدام مبيدات فطرية وقائية مصرحة.',
    treatmentEn: 'Avoid planting susceptible juniper/cedar species nearby, and spray appropriate fungicides.',
  ),
  'Apple___healthy': DiseaseInfo(
    plantNameAr: 'تفاح',
    plantNameEn: 'Apple',
    conditionAr: 'سليم / صحي',
    conditionEn: 'Healthy foliage',
    symptomsAr: 'أوراق خضراء يانعة خالية من البقع أو الثقوب، ونمو طبيعي صحي.',
    symptomsEn: 'Vibrant green leaves, uniform growth, with zero visible lesions.',
    treatmentAr: 'تابع الري المنتظم، والتسميد العضوي الدوري للحفاظ على قوة ونظام مناعة الشجرة.',
    treatmentEn: 'Maintain uniform irrigation, timely organic pruning, and routine nutritional feeding.',
  ),
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': DiseaseInfo(
    plantNameAr: 'ذرة',
    plantNameEn: 'Corn (Maize)',
    conditionAr: 'تبقع الأوراق الرمادي (Gray Leaf Spot)',
    conditionEn: 'Gray Leaf Spot',
    symptomsAr: 'آفات مستطيلة رمادية إلى بنية موازية لعروق الورقة على شكل شرائط شبيهة بالصناديق.',
    symptomsEn: 'Pale brown to gray rectangular lesions running parallel to crop leaf veins.',
    treatmentAr: 'استخدام هجن مقاومة، تناوب المحاصيل لسنوات، وتطبيق مبيدات الفطر التريازولية عند التفشي.',
    treatmentEn: 'Plant resilient hybrids, pursue field rotation, and apply systemic triazole fungicides.',
  ),
  'Corn_(maize)___Common_rust_': DiseaseInfo(
    plantNameAr: 'ذرة',
    plantNameEn: 'Corn (Maize)',
    conditionAr: 'الصدأ الشائع (Common Rust)',
    conditionEn: 'Common Rust',
    symptomsAr: 'بثرات مسحوقية دائرية بارزة ذات لون بني ذهبي أو أحمر صدئي على كلا سطحي الورقة.',
    symptomsEn: 'Powdery golden to reddish-brown raised pustules on both upper and lower leaf surfaces.',
    treatmentAr: 'الحرث العميق لمخلفات النبات، ورش مبيد ستروبيلورين لعلاج التفشي السريع.',
    treatmentEn: 'Deep till old crop residues, and treat high-risk acreage with protective strobilurins.',
  ),
  'Corn_(maize)___Northern_Leaf_Blight': DiseaseInfo(
    plantNameAr: 'ذرة',
    plantNameEn: 'Corn (Maize)',
    conditionAr: 'لفحة الأوراق الشمالية (Northern Leaf Blight)',
    conditionEn: 'Northern Leaf Blight',
    symptomsAr: 'آفات مغزلية عريضة ممتدة بلون رمادي أو زيتوني، تبدأ عادة من الأوراق السفلية المتأرجحة.',
    symptomsEn: 'Elongated, elliptical grayish-green cigar-shaped lesions progressing from lower leaves.',
    treatmentAr: 'التخلص التام من البقايا النباتية المصابة وتناوب زراعة الذرة مع البقوليات.',
    treatmentEn: 'Incorporate crop residues, rotate out of corn, and spray systemic chemical cures.',
  ),
  'Corn_(maize)___healthy': DiseaseInfo(
    plantNameAr: 'ذرة',
    plantNameEn: 'Corn (Maize)',
    conditionAr: 'سليم / صحي',
    conditionEn: 'Healthy corn',
    symptomsAr: 'أوراق مستقيمة طويلة بلون أخضر قوي ونظيف، دون علامات آفات أو بقع بنية.',
    symptomsEn: 'Broad, robust and deep-green leaves with upright development and clean stems.',
    treatmentAr: 'توفير النيتروجين والزنك الكافي مع انتظام تدفق الري لضمان نمو الحبوب بشكل ممتاز.',
    treatmentEn: 'Maintain nitrogen and zinc soil levels and assure steady irrigation during silking.',
  ),
  'Grape___Black_rot': DiseaseInfo(
    plantNameAr: 'عنب',
    plantNameEn: 'Grape',
    conditionAr: 'العفن الأسود (Black Rot)',
    conditionEn: 'Black Rot',
    symptomsAr: 'حلقات دائرية حمراء بنية على الأوراق وثمار العنب المتجعدة واليابسة كالممياوات السوداء.',
    symptomsEn: 'Small circular brown spots on leaves; shriveled, hard, mummified black grapes on vines.',
    treatmentAr: 'إزالة الثمار المحنطة والأغصان المصابة أثناء التقليم بقوة، وتطبيق الرش بالنحاس المعدني.',
    treatmentEn: 'Prune and destroy infected canes and mummies; protect early growth with copper sprays.',
  ),
  'Grape___healthy': DiseaseInfo(
    plantNameAr: 'عنب',
    plantNameEn: 'Grape',
    conditionAr: 'سليم / صحي',
    conditionEn: 'Healthy grapevine',
    symptomsAr: 'أوراق عريضة كفية خضراء سليمة وعناقيد ثمار ناعمة تنمو بشكل جيد ومتزن.',
    symptomsEn: 'Lush lobed leaves showing standard rich color, firm vines, and healthy fruit sets.',
    treatmentAr: 'تقليم الفروع لزيادة تهوية قلب الشجرة وتحسين نفاذ أشعة الشمس للثمار.',
    treatmentEn: 'Prune to let solar light penetrate optimal zones, and support proper vine trellis structure.',
  ),
  'Orange___Haunglongbing_(Citrus_greening)': DiseaseInfo(
    plantNameAr: 'برتقال',
    plantNameEn: 'Orange',
    conditionAr: 'اخضرار الحمضيات / التدهور السريع (HLB)',
    conditionEn: 'Citrus Greening',
    symptomsAr: 'اصفرار متبقع غير متماثل على الأوراق، ثمار مشوهة صغيرة ومرة الطعم تحوي بذوراً ميتة.',
    symptomsEn: 'Asymmetric yellow mottling of leaves, lopsided green bitter fruit with abortive seeds.',
    treatmentAr: 'مكافحة حشرة بسيلا الحمضيات بالزيوت المعدنية ومبيدات نيوميكوتينويد، واقتلاع الأشجار المصابة.',
    treatmentEn: 'Control psyllids with insecticide soaps and delete highly infected trees.',
  ),
  'Peach___healthy': DiseaseInfo(
    plantNameAr: 'خوخ',
    plantNameEn: 'Peach',
    conditionAr: 'سليم / صحي',
    conditionEn: 'Healthy peach',
    symptomsAr: 'أوراق رمحية نظيفة ناعمة السطح بلون أخضر برّاق ونمو فروع قوي وخالٍ من الصمغ.',
    symptomsEn: 'Clean lanceolate leaves, vibrant pink spring blooms, and lack of sticky canker gums.',
    treatmentAr: 'الحفاظ على حوض ري دائري نظيف، ورش الكبريت الوقائي قبل تفتح البراعم.',
    treatmentEn: 'Keep a clear root basin, mulch properly, and support with balanced macro-fertilizers.',
  ),
  'Potato___Early_blight': DiseaseInfo(
    plantNameAr: 'بطاطس',
    plantNameEn: 'Potato',
    conditionAr: 'اللفحة المبكرة (Early Blight)',
    conditionEn: 'Early Blight',
    symptomsAr: 'بقع بنية داكنة تحوي حلقات دائرية متداخلة كلوحة الهدف للرماية، تبدأ بالأوراق المسنة.',
    symptomsEn: 'Concentric target board dark rings on mature lower foliage, moving upward.',
    treatmentAr: 'تطبيق دورة زراعية ثلاثية السنوات، وتوفير تهوية مثالية، ورش الكلوروثالونيل.',
    treatmentEn: 'Enact a 3-year crop rotation, spacing for leaf aeration, and apply chlorothalonil sprays.',
  ),
  'Potato___Late_blight': DiseaseInfo(
    plantNameAr: 'بطاطس',
    plantNameEn: 'Potato',
    conditionAr: 'اللفحة المتأخرة (Late Blight)',
    conditionEn: 'Late Blight',
    symptomsAr: 'بقع مائية شاحبة رطبة سريعة الانتشار على الأوراق يرافقها نمو صوفي أبيض خفيف تحت الورقة.',
    symptomsEn: 'Rapidly expanding water-soaked greasy gray lesions with powdery white mold underneath.',
    treatmentAr: 'مدمر للمحصول؛ يجب التخلص الفوري من الأوراق والدرنات المصابة وتجنب ري الرشاشات العلوية.',
    treatmentEn: 'Highly destructive; burn infected residue, and apply protectant metalaxyl or copper.',
  ),
  'Potato___healthy': DiseaseInfo(
    plantNameAr: 'بطاطس',
    plantNameEn: 'Potato',
    conditionAr: 'سليم / صحي',
    conditionEn: 'Healthy potato',
    symptomsAr: 'مجموع خضري كثيف، أوراق مركبة خضراء خالية من القروح أو البقع الصفراء الزيتية.',
    symptomsEn: 'Vigorous dense bushy green canopy with healthy compound leaves.',
    treatmentAr: 'قم بعملية العزيق للتغطية الترابية حول الدرنات بشكل مستمر لمنع لفحة الشمس.',
    treatmentEn: 'Hill soil around potato vine bases consistently to prevent sun exposure on tubers.',
  ),
  'Tomato___Early_blight': DiseaseInfo(
    plantNameAr: 'طماطم',
    plantNameEn: 'Tomato',
    conditionAr: 'اللفحة المبكرة (Early Blight)',
    conditionEn: 'Early Blight',
    symptomsAr: 'بقع سوداء ذات حلقات دائرية متطابقة مثل البصمة تبدأ بالأوراق السفلى وتؤدي لاصفرار المجموع الخضري.',
    symptomsEn: 'Concentric target-board spots starting on oldest lower crop leaves.',
    treatmentAr: 'التقليم الدوري للأغصان الميتة لضمان التهوئة، وتطبيق مبيدات النحاس الوقائية.',
    treatmentEn: 'Prune lower branches to 12 inches off soil, maximize sun gaps, and utilize chlorothalonil.',
  ),
  'Tomato___Late_blight': DiseaseInfo(
    plantNameAr: 'طماطم',
    plantNameEn: 'Tomato',
    conditionAr: 'اللفحة المتأخرة (Late Blight)',
    conditionEn: 'Late Blight',
    symptomsAr: 'بقع رمادية مسودة زيتية رطبة سريعة التمدد والفتك، وتلف كامل متفحم للثمار.',
    symptomsEn: 'Large, greasy olive to dark gray patches on foliage drying up swiftly, rotting whole fruit.',
    treatmentAr: 'مرض خطير جداً يتطلب عزل النبات وحرقه فوراً، والرش الفطري الوقائي بالنحاس.',
    treatmentEn: 'Act instantly: discard infected tomatoes, do not compost them, and apply copper preemptively.',
  ),
  'Tomato___healthy': DiseaseInfo(
    plantNameAr: 'طماطم',
    plantNameEn: 'Tomato',
    conditionAr: 'سليم / صحي',
    conditionEn: 'Healthy tomato foliage',
    symptomsAr: 'نمو مورق كجذور قوية، أوراق ريشية خضراء داكنة سليمة تماماً وتفتح جيد للزهور الصفراء.',
    symptomsEn: 'Robust multi-branched structure, deep green serrated leaves with zero spots.',
    treatmentAr: 'أضف أسمدة البوتاسيوم بانتظام لدعم تزهير قوي ومستمر، والري من الأسفل.',
    treatmentEn: 'Feed rich organic compost, water deeply at the soil level, and watch for beautiful yellow blossoms.',
  ),
  'Wheat___Leaf_rust': DiseaseInfo(
    plantNameAr: 'قمح',
    plantNameEn: 'Wheat',
    conditionAr: 'صدأ الأوراق (Leaf Rust)',
    conditionEn: 'Leaf Rust',
    symptomsAr: 'بثرات برتقالية اللون دائرية مبعثرة على أسطح الأوراق تسبب اصفرارها ونقص التمثيل الضوئي.',
    symptomsEn: 'Small, round yellowish-orange pustules scattered on leaf surfaces, reducing active photosynthesis.',
    treatmentAr: 'زراعة أصناف مقاومة للصدأ، وتطبيق مبيدات فطرية من فئة التريازول عند بداية تسرب الإصابة.',
    treatmentEn: 'Plant rust-resistant cultivars, and treat high-yield plots early with triazole fungicides.',
  ),
  'Wheat___healthy': DiseaseInfo(
    plantNameAr: 'قمح',
    plantNameEn: 'Wheat',
    conditionAr: 'سليم / صحي',
    conditionEn: 'Healthy Wheat',
    symptomsAr: 'سيقان قائمة خضراء قوية، أوراق حرة خالية من البثرات الصفراء أو البقع وسنابل ممتلئة.',
    symptomsEn: 'Erect bright green stalks, leaves free of any colored rust pustules, and well-filled green grain spikes.',
    treatmentAr: 'استمر في بروتوكول التسميد المعتدل وضبط نسب مياه الري وتصفية التربة بانتظام.',
    treatmentEn: 'Maintain robust micro-nutrition feeds, control field humidity, and implement weed clearance.',
  ),
};
